#
# Pedafy - PhpMyAdmin for Google Cloud SQL
#
# An Epitech Innovation Hub project
#
# florent.poinsard@epitech.eu
#

service: phpmyadmin
runtime: php55
api_version: 1

handlers:
  - url: /(.+\.(ico|jpg|png|gif))$
    static_files: \1
    upload: (.+\.(ico|jpg|png|gif))$
    application_readable: true
    secure: always

  - url: /(.+\.(htm|html|css|js))$
    static_files: \1
    upload: (.+\.(htm|html|css|js))$
    application_readable: true
    secure: always

  - url: /(.+\.php)$
    script: \1
    login: admin
    secure: always

  - url: /.*
    script: index.php
    login: admin
    secure: always